### PR TITLE
Tell not not to connect through Bluetooth settings

### PR DESCRIPTION
**Pull request by josuah**
It appears that this interferes with Noa app. Maybe a property of how Bluetooth Low Energy is handled in iOS.
https://discord.com/channels/963222352534048818/1245235426394902609

### CODE REVIEW

**Review by siliconwitch — COMMENTED** [review]
Maybe clearer to say?

Ensure to connect to Frame only within the Noa app itself, and not from the system Bluetooth settings directly.

**Comment by josuah** [comment]
It might also be a misunderstanding from my side, since the user is actually expected to answer "Pair"... Updating the text and keeping it on hold.

**Comment by siliconwitch** [comment]
As in you're correct, I just meant if we can make the wording:

> Ensure to connect to Frame only from within the Noa app itself, and not from the system Bluetooth settings directly.

rather than

> Make sure to not connect to Frame in the system settings, and only in the Noa app"

**Comment by josuah** [comment]
Out of time, sorry.

**Pull request closed without merging**
